// Auto-generated by web/extract_model_arch.py
// Do not edit manually

export interface ArchLayer {
  type: string;
  label: string;
  params?: Record<string, number | string | boolean>;
}

export interface ArchBranch {
  name: string;
  layers: ArchLayer[];
}

export interface ModelArchitecture {
  modelId: string;
  archType: 'sequential' | 'branching' | 'multi-head' | 'transformer' | 'tree-ensemble' | 'kernel-method' | 'linear-regularized' | 'statistical';
  title: string;
  layers?: ArchLayer[];
  branches?: ArchBranch[];
  shared?: ArchLayer[];
  heads?: ArchBranch[];
  merger?: ArchLayer;
  algorithm?: string;
  params?: Record<string, number | string>;
}

export const MODEL_ARCHITECTURES: Record<string, ModelArchitecture> = {
  'lightgbm-wang2023': {
    modelId: 'lightgbm-wang2023',
    archType: 'tree-ensemble',
    title: 'LightGBM 多因子选股策略',
    algorithm: 'LightGBM',
    params: {
      objective: 'regression',
      metric: 'mse',
      boosting_type: 'gbdt',
      num_leaves: 31,
      learning_rate: 0.05,
      feature_fraction: 0.8,
      bagging_fraction: 0.8,
      bagging_freq: 5,
      lambda_l1: 0.1,
      lambda_l2: 0.1,
    },
  },
  'xgboost-sun2024': {
    modelId: 'xgboost-sun2024',
    archType: 'tree-ensemble',
    title: 'XGBoost + SHAP 多因子选股策略',
    algorithm: 'XGBoost',
    params: {
      objective: 'reg',
      max_depth: 5,
      learning_rate: 0.05,
      subsample: 0.8,
      colsample_bytree: 0.8,
      reg_alpha: 0.1,
      reg_lambda: 1.0,
      verbosity: 0,
    },
  },
  'random-forest-fu2020': {
    modelId: 'random-forest-fu2020',
    archType: 'tree-ensemble',
    title: 'Random Forest 动态因子选股策略',
    algorithm: 'RandomForest',
    params: {
      n_estimators: 200,
      max_depth: 8,
      min_samples_leaf: 10,
      oob_score: 'True',
    },
  },
  'svm-liu2023': {
    modelId: 'svm-liu2023',
    archType: 'kernel-method',
    title: 'SVM 多因子量化选股策略',
    algorithm: 'SVM (RBF)',
    params: {
      kernel: 'rbf',
      C: 1.0,
      gamma: 0.1,
    },
  },
  'lasso-elastic-ridge-xu2023': {
    modelId: 'lasso-elastic-ridge-xu2023',
    archType: 'linear-regularized',
    title: '05 OLS / Ridge / Lasso / Elastic Net 多因子选股',
    algorithm: 'OLS + Ridge + Lasso + ElasticNet',
    params: {
      alpha: 0.01,
      l1_ratio: 0.5,
    },
  },
  'kpca-regression-zhou2020': {
    modelId: 'kpca-regression-zhou2020',
    archType: 'statistical',
    title: '06 Kernel PCA + 线性回归 多因子选股',
    algorithm: 'Kernel PCA + Regression',
    params: {
      n_components: 5,
      kernel: 'rbf',
    },
  },
  'fama-macbeth-cui2022': {
    modelId: 'fama-macbeth-cui2022',
    archType: 'statistical',
    title: '07 Fama-MacBeth 两步回归 多因子选股',
    algorithm: 'Fama-MacBeth Two-Pass Regression',
    params: {
      window: 60,
    },
  },
  'stacking-ensemble-zheng2024': {
    modelId: 'stacking-ensemble-zheng2024',
    archType: 'branching',
    title: 'Stacking Ensemble (RF + XGB + LGB + Meta)',
    branches: [
      {
        name: 'RandomForest',
        layers: [
          { type: 'RandomForest', label: 'RF(n=200)', params: { n_estimators: 200 } },
        ],
      },
      {
        name: 'XGBoost',
        layers: [
          { type: 'XGBoost', label: 'XGB(depth=6)', params: { max_depth: 6 } },
        ],
      },
      {
        name: 'LightGBM',
        layers: [
          { type: 'LightGBM', label: 'LGB(leaves=31)', params: { num_leaves: 31 } },
        ],
      },
    ],
    merger: { type: 'Linear', label: 'Meta-Learner (Ridge)', params: { alpha: 1.0 } },
    algorithm: 'LightGBM',
    params: {
      boosting_type: 'gbdt',
      num_leaves: 31,
      learning_rate: 0.05,
    },
  },
  'lstm-gru-cheng2024': {
    modelId: 'lstm-gru-cheng2024',
    archType: 'sequential',
    title: 'LSTM/GRU 股票预测策略',
    layers: [
      { type: 'LSTM', label: 'LSTM(input_size->hidden_size)', params: { num_layers: 1, input_size: 'input_size', hidden_size: 'hidden_size' } },
      { type: 'Dropout', label: 'Dropout(0.0)', params: { p: 0.0 } },
      { type: 'Linear', label: 'FC(hidden_size->1)', params: { in_features: 'hidden_size', out_features: 1 } },
    ],
  },
  'quantformer-zhang2024': {
    modelId: 'quantformer-zhang2024',
    archType: 'transformer',
    title: 'Quantformer: 从注意力到收益',
    layers: [
      { type: 'Linear', label: 'FC(input_size->d_model)', params: { in_features: 'input_size', out_features: 'd_model' } },
      { type: 'TransformerEncoder', label: 'TransformerEncoder(layers=num_layers)', params: { num_layers: 'num_layers' } },
      { type: 'Linear', label: 'FC(d_model->32)', params: { in_features: 'd_model', out_features: 32 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.0)', params: { p: 0.0 } },
      { type: 'Linear', label: 'FC(32->1)', params: { in_features: 32, out_features: 1 } },
    ],
  },
  'alphanet-v4-wu2024': {
    modelId: 'alphanet-v4-wu2024',
    archType: 'transformer',
    title: 'AlphaNetV4: Alpha Mining Model',
    layers: [
      { type: 'Linear', label: 'FC(bilstm_out->d_model)', params: { in_features: 'bilstm_out', out_features: 'd_model' } },
      { type: 'TransformerEncoder', label: 'TransformerEncoder(layers=num_transformer_layers)', params: { num_layers: 'num_transformer_layers' } },
      { type: 'Linear', label: 'FC(d_model->64)', params: { in_features: 'd_model', out_features: 64 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.0)', params: { p: 0.0 } },
      { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
    ],
  },
  'cnn-lstm-zhuang2022': {
    modelId: 'cnn-lstm-zhuang2022',
    archType: 'sequential',
    title: 'CNN-LSTM 量化选股策略',
    layers: [
      { type: 'Conv1d', label: 'Conv1d(input_size->cnn_filters, k=kernel_size)', params: { in_channels: 'input_size', out_channels: 'cnn_filters', kernel_size: 'kernel_size' } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'MaxPool1d', label: 'MaxPool1d(k=2)', params: { kernel_size: 2 } },
      { type: 'Dropout', label: 'Dropout(0.0)', params: { p: 0.0 } },
      { type: 'LSTM', label: 'LSTM(cnn_filters->lstm_hidden)', params: { num_layers: 1, input_size: 'cnn_filters', hidden_size: 'lstm_hidden' } },
      { type: 'Dropout', label: 'Dropout(0.0)', params: { p: 0.0 } },
      { type: 'Linear', label: 'FC(lstm_hidden->32)', params: { in_features: 'lstm_hidden', out_features: 32 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.0)', params: { p: 0.0 } },
      { type: 'Linear', label: 'FC(32->1)', params: { in_features: 32, out_features: 1 } },
    ],
  },
  'cnn-bilstm-attention-zhang2023': {
    modelId: 'cnn-bilstm-attention-zhang2023',
    archType: 'sequential',
    title: 'CNN-BiLSTM-Attention 股票预测策略',
    layers: [
      { type: 'Conv1d', label: 'Conv1d(input_size->cnn_filters, k=kernel_size)', params: { in_channels: 'input_size', out_channels: 'cnn_filters', kernel_size: 'kernel_size' } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.0)', params: { p: 0.0 } },
      { type: 'Linear', label: 'FC(lstm_hidden * 2->32)', params: { in_features: 'lstm_hidden * 2', out_features: 32 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.0)', params: { p: 0.0 } },
      { type: 'Linear', label: 'FC(32->1)', params: { in_features: 32, out_features: 1 } },
    ],
  },
  'fcnn-chen2023': {
    modelId: 'fcnn-chen2023',
    archType: 'sequential',
    title: '06 全连接神经网络 (FCNN) 量化交易策略',
    layers: [
      { type: 'Linear', label: 'FC(input_dim->128)', params: { in_features: 'input_dim', out_features: 128 } },
      { type: 'BatchNorm1d', label: 'BatchNorm1d(128)', params: { num_features: 128 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.3)', params: { p: 0.3 } },
      { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
      { type: 'BatchNorm1d', label: 'BatchNorm1d(64)', params: { num_features: 64 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.3)', params: { p: 0.3 } },
      { type: 'Linear', label: 'FC(64->32)', params: { in_features: 64, out_features: 32 } },
      { type: 'BatchNorm1d', label: 'BatchNorm1d(32)', params: { num_features: 32 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.3)', params: { p: 0.3 } },
      { type: 'Linear', label: 'FC(32->1)', params: { in_features: 32, out_features: 1 } },
      { type: 'Sigmoid', label: 'Sigmoid' },
    ],
  },
  'ranknet-li2021': {
    modelId: 'ranknet-li2021',
    archType: 'sequential',
    title: '07 深度排序网络 (RankNet) 股票选择策略',
    layers: [
      { type: 'Linear', label: 'FC(input_dim->64)', params: { in_features: 'input_dim', out_features: 64 } },
      { type: 'BatchNorm1d', label: 'BatchNorm1d(64)', params: { num_features: 64 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.2)', params: { p: 0.2 } },
      { type: 'Linear', label: 'FC(64->32)', params: { in_features: 64, out_features: 32 } },
      { type: 'BatchNorm1d', label: 'BatchNorm1d(32)', params: { num_features: 32 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.2)', params: { p: 0.2 } },
      { type: 'Linear', label: 'FC(32->1)', params: { in_features: 32, out_features: 1 } },
    ],
  },
  'wavelet-blstm-liang2023': {
    modelId: 'wavelet-blstm-liang2023',
    archType: 'branching',
    title: '08 小波分解 + 双向LSTM (Wavelet-BiLSTM) 日内收益预测',
    branches: [
      {
        name: 'Branch 1 (BiLSTMBranch)',
        layers: [
          { type: 'Linear', label: 'FC(hidden_dim * 2->16)', params: { in_features: 'hidden_dim * 2', out_features: 16 } },
        ],
      },
      {
        name: 'Branch 2 (BiLSTMBranch)',
        layers: [
          { type: 'Linear', label: 'FC(hidden_dim * 2->16)', params: { in_features: 'hidden_dim * 2', out_features: 16 } },
        ],
      },
      {
        name: 'Branch 3 (BiLSTMBranch)',
        layers: [
          { type: 'Linear', label: 'FC(hidden_dim * 2->16)', params: { in_features: 'hidden_dim * 2', out_features: 16 } },
        ],
      },
      {
        name: 'Branch 4 (BiLSTMBranch)',
        layers: [
          { type: 'Linear', label: 'FC(hidden_dim * 2->16)', params: { in_features: 'hidden_dim * 2', out_features: 16 } },
        ],
      },
    ],
    merger: { type: 'Linear', label: 'FC(16 * n_components->32)', params: { in_features: '16 * n_components', out_features: 32 } },
  },
  'mftr-guo2023': {
    modelId: 'mftr-guo2023',
    archType: 'branching',
    title: 'MFTR: Multi-Frequency Timing Residual Network',
    layers: [
      { type: 'Linear', label: 'FC(hidden_dim * 3->64)', params: { in_features: 'hidden_dim * 3', out_features: 64 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.3)', params: { p: 0.3 } },
      { type: 'Linear', label: 'FC(64->32)', params: { in_features: 64, out_features: 32 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.2)', params: { p: 0.2 } },
      { type: 'Linear', label: 'FC(32->1)', params: { in_features: 32, out_features: 1 } },
      { type: 'Sigmoid', label: 'Sigmoid' },
    ],
    branches: [
      {
        name: '1D Branch (Daily)',
        layers: [
          { type: 'LSTM', label: 'LSTM(features->32)', params: { input_size: 'features', hidden_size: 32 } },
          { type: 'LayerNorm', label: 'LayerNorm(32)', params: { normalized_shape: 32 } },
        ],
      },
      {
        name: '5D Branch (Weekly)',
        layers: [
          { type: 'LSTM', label: 'LSTM(features->32)', params: { input_size: 'features', hidden_size: 32 } },
          { type: 'LayerNorm', label: 'LayerNorm(32)', params: { normalized_shape: 32 } },
        ],
      },
      {
        name: '20D Branch (Monthly)',
        layers: [
          { type: 'LSTM', label: 'LSTM(features->32)', params: { input_size: 'features', hidden_size: 32 } },
          { type: 'LayerNorm', label: 'LayerNorm(32)', params: { normalized_shape: 32 } },
        ],
      },
    ],
    shared: [
      { type: 'Linear', label: 'FC(96->64)', params: { in_features: 96, out_features: 64 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Dropout', label: 'Dropout(0.3)', params: { p: 0.3 } },
      { type: 'Linear', label: 'FC(64->32)', params: { in_features: 64, out_features: 32 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Linear', label: 'FC(32->1)', params: { in_features: 32, out_features: 1 } },
      { type: 'Sigmoid', label: 'Sigmoid' },
    ],
    merger: { type: 'ResidualConnection', label: 'Residual: 20D->5D->1D' },
  },
  'diff-lstm-emd-chen2024': {
    modelId: 'diff-lstm-emd-chen2024',
    archType: 'branching',
    title: 'EMD + Differential LSTM',
    branches: [
      {
        name: 'Branch 1 (SingleIMFLSTM)',
        layers: [
          { type: 'Linear', label: 'FC(hidden_dim->16)', params: { in_features: 'hidden_dim', out_features: 16 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(16->1)', params: { in_features: 16, out_features: 1 } },
        ],
      },
      {
        name: 'Branch 2 (SingleIMFLSTM)',
        layers: [
          { type: 'Linear', label: 'FC(hidden_dim->16)', params: { in_features: 'hidden_dim', out_features: 16 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(16->1)', params: { in_features: 16, out_features: 1 } },
        ],
      },
      {
        name: 'Branch 3 (SingleIMFLSTM)',
        layers: [
          { type: 'Linear', label: 'FC(hidden_dim->16)', params: { in_features: 'hidden_dim', out_features: 16 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(16->1)', params: { in_features: 16, out_features: 1 } },
        ],
      },
      {
        name: 'Branch 4 (SingleIMFLSTM)',
        layers: [
          { type: 'Linear', label: 'FC(hidden_dim->16)', params: { in_features: 'hidden_dim', out_features: 16 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(16->1)', params: { in_features: 16, out_features: 1 } },
        ],
      },
    ],
  },
  'ppo-a2c-sac-ensemble-li2022': {
    modelId: 'ppo-a2c-sac-ensemble-li2022',
    archType: 'multi-head',
    title: 'Ensemble RL: PPO + A2C + DQN',
    shared: [
      { type: 'Linear', label: 'FC(state->128)', params: { in_features: 'state_dim', out_features: 128 } },
      { type: 'ReLU', label: 'ReLU' },
    ],
    heads: [
      {
        name: 'DQN',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->3)', params: { in_features: 64, out_features: 3 } },
        ],
      },
      {
        name: 'A2C Actor',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->3)', params: { in_features: 64, out_features: 3 } },
          { type: 'Softmax', label: 'Softmax' },
        ],
      },
      {
        name: 'A2C Critic',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
        ],
      },
      {
        name: 'PPO Actor-Critic',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->3+1)', params: { in_features: 64, out_features: 4 } },
        ],
      },
    ],
    merger: { type: 'MajorityVote', label: 'Majority Vote Ensemble' },
  },
  'mtl-ddpg-deng2023': {
    modelId: 'mtl-ddpg-deng2023',
    archType: 'multi-head',
    title: 'Multi-Task Learning DDPG',
    shared: [
      { type: 'Linear', label: 'SharedFC(state->128)', params: { in_features: 'state_dim', out_features: 128 } },
      { type: 'ReLU', label: 'ReLU' },
    ],
    heads: [
      {
        name: 'Trading Actor',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->action)', params: { in_features: 64, out_features: 'action_dim' } },
        ],
      },
      {
        name: 'Price Predictor',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
        ],
      },
      {
        name: 'Critic',
        layers: [
          { type: 'Linear', label: 'FC(128+action->64)' },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
        ],
      },
    ],
  },
  'edpg-gru-ddpg-zhu2022': {
    modelId: 'edpg-gru-ddpg-zhu2022',
    archType: 'multi-head',
    title: 'EDPG: GRU Encoder + DDPG',
    shared: [
      { type: 'GRU', label: 'GRU Encoder(state->64)', params: { input_size: 'state_dim', hidden_size: 64 } },
    ],
    heads: [
      {
        name: 'Actor (DDPG)',
        layers: [
          { type: 'Linear', label: 'FC(64->32)', params: { in_features: 64, out_features: 32 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(32->action)', params: { in_features: 32, out_features: 'action_dim' } },
          { type: 'Tanh', label: 'Tanh' },
        ],
      },
      {
        name: 'Critic (DDPG)',
        layers: [
          { type: 'Linear', label: 'FC(64+action->32)', params: { in_features: '64+action', out_features: 32 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(32->1)', params: { in_features: 32, out_features: 1 } },
        ],
      },
    ],
  },
  'ppo-futures-chen2023': {
    modelId: 'ppo-futures-chen2023',
    archType: 'multi-head',
    title: 'PPO for Futures Trading',
    shared: [
      { type: 'Linear', label: 'FC(state->128)', params: { in_features: 'state_dim', out_features: 128 } },
      { type: 'ReLU', label: 'ReLU' },
    ],
    heads: [
      {
        name: 'PPO Actor',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->action)', params: { in_features: 64, out_features: 'action_dim' } },
          { type: 'Softmax', label: 'Softmax' },
        ],
      },
      {
        name: 'PPO Critic',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
        ],
      },
    ],
  },
  'garch-ppo-wang2021': {
    modelId: 'garch-ppo-wang2021',
    archType: 'multi-head',
    title: 'GARCH-Enhanced PPO',
    layers: [
      { type: 'Linear', label: 'FC(state_dim->256)', params: { in_features: 'state_dim', out_features: 256 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'LayerNorm', label: 'LayerNorm(256)', params: { normalized_shape: 256 } },
      { type: 'Linear', label: 'FC(256->128)', params: { in_features: 256, out_features: 128 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'LayerNorm', label: 'LayerNorm(128)', params: { normalized_shape: 128 } },
      { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Linear', label: 'FC(64->action_dim)', params: { in_features: 64, out_features: 'action_dim' } },
      { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
    ],
    shared: [
      { type: 'GARCH', label: 'GARCH(1,1) Volatility', params: { p: 1, q: 1 } },
      { type: 'Linear', label: 'FC(state+vol->128)', params: { in_features: 'state+1', out_features: 128 } },
      { type: 'ReLU', label: 'ReLU' },
    ],
    heads: [
      {
        name: 'PPO Actor',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->action)', params: { in_features: 64, out_features: 'action_dim' } },
          { type: 'Softmax', label: 'Softmax' },
        ],
      },
      {
        name: 'PPO Critic',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
        ],
      },
    ],
  },
  'mctg-wang2021a': {
    modelId: 'mctg-wang2021a',
    archType: 'multi-head',
    title: 'Monte Carlo Tree-Guided RL',
    shared: [
      { type: 'Linear', label: 'FC(state->128)', params: { in_features: 'state_dim', out_features: 128 } },
      { type: 'ReLU', label: 'ReLU' },
    ],
    heads: [
      {
        name: 'MCTS Policy',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->action)', params: { in_features: 64, out_features: 'action_dim' } },
          { type: 'Softmax', label: 'Softmax' },
        ],
      },
      {
        name: 'Value Network',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
        ],
      },
    ],
  },
  'drpo-han2023': {
    modelId: 'drpo-han2023',
    archType: 'multi-head',
    title: 'Distributionally Robust Policy Optimization',
    shared: [
      { type: 'Linear', label: 'FC(state->256)', params: { in_features: 'state_dim', out_features: 256 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Linear', label: 'FC(256->128)', params: { in_features: 256, out_features: 128 } },
      { type: 'ReLU', label: 'ReLU' },
    ],
    heads: [
      {
        name: 'Robust Actor',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->action)', params: { in_features: 64, out_features: 'action_dim' } },
          { type: 'Tanh', label: 'Tanh' },
        ],
      },
      {
        name: 'Robust Critic',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
        ],
      },
    ],
    algorithm: 'Actor-Critic CVaR Optimization',
    params: {
      alpha: 0.05,
    },
  },
  'bandit-tradebot-zhang2021': {
    modelId: 'bandit-tradebot-zhang2021',
    archType: 'statistical',
    title: 'Multi-Armed Bandit TradeBot',
    algorithm: 'Thompson Sampling + UCB',
    params: {
      n_arms: 3,
      exploration: 'UCB1',
    },
  },
  'inverse-rl-zhang2023': {
    modelId: 'inverse-rl-zhang2023',
    archType: 'multi-head',
    title: 'Inverse Reinforcement Learning',
    shared: [
      { type: 'Linear', label: 'FC(state->128)', params: { in_features: 'state_dim', out_features: 128 } },
      { type: 'ReLU', label: 'ReLU' },
    ],
    heads: [
      {
        name: 'Reward Network (IRL)',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
        ],
      },
      {
        name: 'Policy Network',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->action)', params: { in_features: 64, out_features: 'action_dim' } },
          { type: 'Softmax', label: 'Softmax' },
        ],
      },
    ],
  },
  'autoalpha-zhang2020': {
    modelId: 'autoalpha-zhang2020',
    archType: 'statistical',
    title: 'AutoAlpha: 遗传编程挖掘 Alpha 因子',
    algorithm: 'Genetic Programming Alpha Mining',
    params: {
      population: 500,
      generations: 50,
    },
  },
  'warm-gp-ren2024': {
    modelId: 'warm-gp-ren2024',
    archType: 'statistical',
    title: 'Warm Start GP: 热启动遗传编程增强 Alpha 挖掘',
    algorithm: 'Warm-Start Genetic Programming',
    params: {
      population: 300,
    },
  },
  'llm-alpha-kou2024': {
    modelId: 'llm-alpha-kou2024',
    archType: 'statistical',
    title: 'LLM Alpha Mining: 模拟大语言模型驱动的因子挖掘',
    algorithm: 'LLM-Guided Alpha Generation',
    params: {
    },
  },
  'chatgpt-nlp-lstm-zhang2023': {
    modelId: 'chatgpt-nlp-lstm-zhang2023',
    archType: 'sequential',
    title: 'ChatGPT Sentiment + LSTM',
    layers: [
      { type: 'Embedding', label: 'Sentiment Score (GPT)' },
      { type: 'LSTM', label: 'LSTM(input->64)', params: { input_size: 'features', hidden_size: 64, num_layers: 1 } },
      { type: 'Dropout', label: 'Dropout(0.2)', params: { p: 0.2 } },
      { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
      { type: 'Sigmoid', label: 'Sigmoid' },
    ],
  },
  'lambdamart-zhang2021': {
    modelId: 'lambdamart-zhang2021',
    archType: 'tree-ensemble',
    title: 'LambdaMART 排序学习选股策略',
    algorithm: 'LambdaMART',
    params: {
      n_estimators: 300,
      num_leaves: 31,
      learning_rate: 0.1,
    },
  },
  'cointegration-kalman-he2023': {
    modelId: 'cointegration-kalman-he2023',
    archType: 'statistical',
    title: '01 协整 + 卡尔曼滤波 动态对冲比率配对交易',
    algorithm: 'Cointegration + Kalman Filter',
    params: {
      entry_z: 2.0,
      exit_z: 0.5,
    },
  },
  'ecm-pairs-wang2023': {
    modelId: 'ecm-pairs-wang2023',
    archType: 'statistical',
    title: '02 误差修正模型 (ECM) 配对交易',
    algorithm: 'Error Correction Model (ECM)',
    params: {
      lookback: 60,
      entry_z: 2.0,
      exit_z: 0.5,
    },
  },
  'lstm-arbitrage-han2024': {
    modelId: 'lstm-arbitrage-han2024',
    archType: 'sequential',
    title: 'LSTM Statistical Arbitrage',
    layers: [
      { type: 'LSTM', label: 'LSTM(features->64)', params: { input_size: 'features', hidden_size: 64, num_layers: 2 } },
      { type: 'Dropout', label: 'Dropout(0.2)', params: { p: 0.2 } },
      { type: 'Linear', label: 'FC(64->32)', params: { in_features: 64, out_features: 32 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Linear', label: 'FC(32->1)', params: { in_features: 32, out_features: 1 } },
      { type: 'Tanh', label: 'Tanh' },
    ],
  },
  'svm-pairs-yu2022': {
    modelId: 'svm-pairs-yu2022',
    archType: 'kernel-method',
    title: '04 SVM 分类器增强配对交易',
    algorithm: 'SVM Pairs Trading',
    params: {
      kernel: 'rbf',
      C: 1.0,
    },
  },
  'improved-bollinger-gong2024': {
    modelId: 'improved-bollinger-gong2024',
    archType: 'statistical',
    title: '改进布林带趋势增强策略',
    algorithm: 'Improved Bollinger Bands',
    params: {
      window: 20,
      num_std: 2,
    },
  },
  'lever-yuan2024': {
    modelId: 'lever-yuan2024',
    archType: 'statistical',
    title: 'LEVER: 在线自适应序列学习框架',
    algorithm: 'LEVER Online Learning',
    params: {
    },
  },
  'rl-hft-tuning-zhang2023': {
    modelId: 'rl-hft-tuning-zhang2023',
    archType: 'multi-head',
    title: 'RL-Based HFT Parameter Tuning',
    layers: [
      { type: 'Linear', label: 'FC(state_dim->64)', params: { in_features: 'state_dim', out_features: 64 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Linear', label: 'FC(64->64)', params: { in_features: 64, out_features: 64 } },
      { type: 'ReLU', label: 'ReLU' },
      { type: 'Linear', label: 'FC(64->n_actions)', params: { in_features: 64, out_features: 'n_actions' } },
    ],
    shared: [
      { type: 'Linear', label: 'FC(state->128)', params: { in_features: 'state_dim', out_features: 128 } },
      { type: 'ReLU', label: 'ReLU' },
    ],
    heads: [
      {
        name: 'Parameter Actor',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->params)', params: { in_features: 64, out_features: 'n_params' } },
          { type: 'Sigmoid', label: 'Sigmoid' },
        ],
      },
      {
        name: 'PnL Critic',
        layers: [
          { type: 'Linear', label: 'FC(128->64)', params: { in_features: 128, out_features: 64 } },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(64->1)', params: { in_features: 64, out_features: 1 } },
        ],
      },
    ],
  },
  'hft-infra-chen2024': {
    modelId: 'hft-infra-chen2024',
    archType: 'statistical',
    title: '04 高频交易基础设施: 订单簿与撮合引擎',
    algorithm: 'HFT Infrastructure (Low-Latency)',
    params: {
    },
  },
  'bl-ledoit-wolf-zeng2022': {
    modelId: 'bl-ledoit-wolf-zeng2022',
    archType: 'statistical',
    title: 'Black-Litterman + Ledoit-Wolf 协方差收缩模型',
    algorithm: 'Black-Litterman + Ledoit-Wolf',
    params: {
      tau: 0.05,
      risk_aversion: 2.5,
    },
  },
  'ac-cvar-ju2022': {
    modelId: 'ac-cvar-ju2022',
    archType: 'multi-head',
    title: 'Actor-Critic CVaR Portfolio',
    shared: [
      { type: 'Linear', label: 'FC(state->64)' },
      { type: 'ReLU', label: 'ReLU' },
    ],
    heads: [
      {
        name: 'Actor (Weights)',
        layers: [
          { type: 'Linear', label: 'FC(64->32)' },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(32->n_assets)' },
          { type: 'Softmax', label: 'Softmax' },
        ],
      },
      {
        name: 'Critic (CVaR)',
        layers: [
          { type: 'Linear', label: 'FC(64->32)' },
          { type: 'ReLU', label: 'ReLU' },
          { type: 'Linear', label: 'FC(32->1)' },
        ],
      },
    ],
    algorithm: 'Actor-Critic CVaR Optimization',
    params: {
      alpha: 0.05,
    },
  },
  'mv-ml-predictions-han2023': {
    modelId: 'mv-ml-predictions-han2023',
    archType: 'tree-ensemble',
    title: '机器学习预测 + Markowitz 均值-方差优化',
    algorithm: 'LightGBM',
    params: {
      objective: 'regression',
      metric: 'mse',
      num_leaves: 31,
      learning_rate: 0.05,
      feature_fraction: 0.8,
      bagging_fraction: 0.8,
      bagging_freq: 5,
    },
  },
  'scoring-screening-li2022': {
    modelId: 'scoring-screening-li2022',
    archType: 'statistical',
    title: '多阶段评分筛选模型',
    algorithm: 'Multi-Factor Scoring & Screening',
    params: {
    },
  },
  'monte-carlo-kmeans-wang2022': {
    modelId: 'monte-carlo-kmeans-wang2022',
    archType: 'statistical',
    title: 'K-Means聚类 + Monte Carlo 组合优化',
    algorithm: 'Monte Carlo + K-Means Clustering',
    params: {
      n_simulations: 10000,
    },
  },
  'higher-moments-liu2020': {
    modelId: 'higher-moments-liu2020',
    archType: 'statistical',
    title: '高阶矩组合优化 (均值-方差-偏度-峰度)',
    algorithm: 'Higher-Moment Portfolio Optimization',
    params: {
      skewness_weight: 0.5,
      kurtosis_weight: 0.5,
    },
  },
};
